#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-DMAC
version:      1.0
version_from: DMAC.pm
installdirs:  site
requires:
    Crypt::CBC:                    2.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
